# Generated by Django 4.2.3 on 2023-08-16 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 16, 4, 11, 29, 226317, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
