# Generated by Django 4.2.3 on 2023-08-16 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_customusermodel_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
