# Generated by Django 4.2.3 on 2023-08-16 04:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 16, 4, 9, 35, 64175, tzinfo=datetime.timezone.utc), editable=False)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.category')),
            ],
        ),
        migrations.CreateModel(
            name='CafeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cafe_item/')),
                ('is_available', models.BooleanField()),
                ('price', models.IntegerField()),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 16, 4, 9, 35, 64626, tzinfo=datetime.timezone.utc), editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.category')),
            ],
        ),
    ]
