# Generated by Django 4.2.3 on 2023-08-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0002_alter_cafeitem_date_added_alter_category_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafeitem",
            name="description",
            field=models.CharField(max_length=250),
        ),
    ]
