# Generated by Django 4.2.3 on 2023-08-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeitem',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
