# Generated by Django 4.2.3 on 2023-08-16 21:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("menus", "0002_alter_cafeitem_date_added_alter_category_date_added"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "footer_name",
                    models.CharField(default="main", max_length=25, unique=True),
                ),
                ("footer_is_active", models.BooleanField(default=True)),
                (
                    "contact_us_title",
                    models.CharField(default="GET IN TOUCH", max_length=25),
                ),
                ("address", models.TextField(default="123 Street, New York, USA")),
                (
                    "phone_number",
                    phone_field.models.PhoneField(default="0211234567", max_length=31),
                ),
                (
                    "email",
                    models.EmailField(default="info@example.com", max_length=254),
                ),
                ("contact_us_is_active", models.BooleanField(default=True)),
                (
                    "follow_us_title",
                    models.CharField(default="FOLLOW US", max_length=25),
                ),
                ("twitter_link", models.CharField(default="#", max_length=250)),
                ("facebook_link", models.CharField(default="#", max_length=250)),
                ("linkedin_link", models.CharField(default="#", max_length=250)),
                ("instagram_link", models.CharField(default="#", max_length=250)),
                ("follow_us_is_active", models.BooleanField(default=True)),
                (
                    "open_hours_title",
                    models.CharField(default="OPEN HOURS", max_length=25),
                ),
                ("days1", models.CharField(default="Monday- Friday", max_length=25)),
                (
                    "hours1",
                    models.CharField(default="8:00 AM- 10:00 PM", max_length=25),
                ),
                (
                    "days2",
                    models.CharField(
                        blank=True, default="Saturday- Sunday", max_length=25, null=True
                    ),
                ),
                (
                    "hours2",
                    models.CharField(
                        blank=True,
                        default="2:00 PM- 10:00 PM",
                        max_length=25,
                        null=True,
                    ),
                ),
                ("open_hours_is_active", models.BooleanField(default=True)),
                (
                    "newsletter_title",
                    models.CharField(default="NEWSLETTER", max_length=25),
                ),
                (
                    "newsletter_description",
                    models.CharField(
                        blank=True,
                        default="Enter your email to get the latest news",
                        max_length=250,
                        null=True,
                    ),
                ),
                ("newsletter_is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "homepage_name",
                    models.CharField(default="main", max_length=25, unique=True),
                ),
                (
                    "webpage_title",
                    models.CharField(default="TEHRAN Coffee Shop", max_length=25),
                ),
                ("search_section_is_active", models.BooleanField(default=True)),
                (
                    "search_section_title",
                    models.CharField(default="SEARCH", max_length=25),
                ),
                (
                    "search_section_description",
                    models.TextField(default="Search for Drinks"),
                ),
                (
                    "search_placeholder",
                    models.CharField(default="Search Here", max_length=100),
                ),
                ("about_us_section_is_active", models.BooleanField(default=True)),
                (
                    "about_us_section_title",
                    models.CharField(default="ABOUT US", max_length=25),
                ),
                (
                    "about_us_section_description",
                    models.TextField(default="Serving Since 2023"),
                ),
                (
                    "about_us_image",
                    models.ImageField(default="#", upload_to="home_images"),
                ),
                (
                    "left_about_us_title",
                    models.CharField(default="Our Story", max_length=25),
                ),
                ("left_about_us_description", models.TextField(blank=True, null=True)),
                (
                    "left_about_us_button_text",
                    models.CharField(default="Learn More", max_length=25),
                ),
                (
                    "right_about_us_title",
                    models.CharField(default="Our Vision", max_length=25),
                ),
                ("right_about_us_description", models.TextField(blank=True, null=True)),
                (
                    "right_about_us_first_option",
                    models.CharField(
                        default="Lorem ipsum dolor sit amet", max_length=50
                    ),
                ),
                (
                    "right_about_us_second_option",
                    models.CharField(
                        default="Lorem ipsum dolor sit amet", max_length=50
                    ),
                ),
                (
                    "right_about_us_third_option",
                    models.CharField(
                        default="Lorem ipsum dolor sit amet", max_length=50
                    ),
                ),
                (
                    "right_about_us_button_text",
                    models.CharField(default="Learn More", max_length=25),
                ),
                ("our_services_section_is_active", models.BooleanField(default=True)),
                (
                    "our_services_section_title",
                    models.CharField(default="OUR SERVICES", max_length=25),
                ),
                (
                    "our_services_section_description",
                    models.TextField(default="Fresh & Organic Beans"),
                ),
                ("offer_section_is_active", models.BooleanField(default=True)),
                (
                    "offer_section_title",
                    models.CharField(default="50% OFF", max_length=25),
                ),
                (
                    "offer_section_short_description",
                    models.TextField(default="Sunday Special Offer"),
                ),
                (
                    "offer_section_long_description",
                    models.TextField(
                        default="Only for Sunday from 1st Jan to 30th Jan 2045"
                    ),
                ),
                (
                    "menu_special_items_section_is_active",
                    models.BooleanField(default=True),
                ),
                (
                    "menu_special_items_section_title",
                    models.CharField(default="TOP RATED ITEMS", max_length=25),
                ),
                (
                    "menu_special_items_section_description",
                    models.TextField(
                        default="The Best Items According to Our Customers"
                    ),
                ),
                ("testimonial_section_is_active", models.BooleanField(default=True)),
                (
                    "testimonial_section_title",
                    models.CharField(default="TESTIMONIAL", max_length=25),
                ),
                (
                    "testimonial_section_description",
                    models.TextField(default="Our Clients Say"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="#", upload_to="home_images")),
                ("icon_class", models.CharField(blank=True, max_length=50, null=True)),
                ("service_title", models.CharField(max_length=100)),
                (
                    "page",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services_list",
                        to="coffeeshop.homepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Low"),
                            (2, "Low"),
                            (3, "Middle"),
                            (4, "High"),
                            (5, "Very High"),
                        ],
                        default=4,
                    ),
                ),
                ("review", models.CharField(max_length=300)),
                (
                    "date_added",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "cafeitem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menus.cafeitem"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarouselItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="#", upload_to="home_images")),
                ("first_line_text", models.TextField(default="We Have Been Serving")),
                ("second_line_text", models.CharField(default="COFFEE", max_length=25)),
                ("third_line_text", models.TextField(default="* SINCE 2023 *")),
                (
                    "page",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carousel_items",
                        to="coffeeshop.homepage",
                    ),
                ),
            ],
        ),
    ]
