# Generated by Django 4.2.3 on 2023-08-02 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(default='preview-page0.jpg', upload_to='cafe_item/')),
                ('is_available', models.BooleanField()),
                ('price', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('table_number', models.IntegerField(default=None)),
                ('total_price', models.IntegerField()),
                ('status', models.CharField(choices=[('d', 'Draft'), ('c', 'Cancel'), ('a', 'accept')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='preview-page0.jpg', upload_to='parent_category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='preview-page0.jpg', upload_to='sub_category')),
                ('parent_category_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.parentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=300)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=4)),
                ('cafeitem_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.cafeitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cafeitem_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.cafeitem')),
                ('order_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.order')),
            ],
        ),
    ]
