# Generated by Django 4.2.3 on 2023-08-03 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('09(\\d{9})$', 'The phone number provided is invalid')], verbose_name='phone number'),
        ),
    ]
