# Generated by Django 4.2.3 on 2023-08-09 16:09

from django.db import migrations, models
import phone_field.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("coffeeshop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="icons/")),
                (
                    "background",
                    models.ImageField(blank=True, null=True, upload_to="background/"),
                ),
                (
                    "gallery",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DynamicNumbers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    phone_field.models.PhoneField(
                        blank=True,
                        help_text="Phone numbers used on webpage",
                        max_length=31,
                        null=True,
                    ),
                ),
                (
                    "cell_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DynamicTexts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
