# Generated by Django 4.2.3 on 2023-08-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffeeshop", "0003_homepage_logo_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_name", models.CharField(max_length=25, unique=True)),
                ("webpage_title", models.CharField(max_length=25)),
                ("headername", models.CharField(max_length=25)),
                ("nestname", models.CharField(max_length=25)),
            ],
        ),
    ]
